version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db

  mongo-seed:
    build: ./mongo-seed
    links:
      - db

  node-app:
    build: .
    environment:
      - NODE_PORT=3000
      - MONGODB_URL=mongodb://root:rootpassword@db:27017/admin
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mongodb_data_container:
